services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: mtbirb
      POSTGRES_PASSWORD: mtbirb
      POSTGRES_DB: mtbirb
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
